export const items = [
    {
        id: "ocular-prosthetic",
        isVideo: false,
        images: [
            "/images/Ocular Prosthetic for Reading Another Human_01.jpeg",
            "/images/Ocular Prosthetic for Reading Another Human_02.jpeg",
        ],
        caption: [
            "Ocular Prosthetic for Reading Another Human",
            "Sculpture",
            "Plastic tubing, wire, glasses",
            "2024"
        ],
        thumbnail: "/images/thumbnails/Ocular Prosthetic for Reading Another Human_thumb.jpeg",
        alt: "Ocular Prosthetic for Reading Another Human",
        padding: "pb-10 ",
        link: "",
        hasAnimation: true,
    },
    {
        id: "steps",
        isVideo: true,
        images: [],
        caption: [
            "11,182,156 Steps",
            "Digital",
            "Toshiba 1979 TV, DVD player, Speaker",
            "2024"
            ],
        thumbnail: "/videos/polychrome_dark.mp4",
        alt: "11,182,156 Steps",
        padding: "pb-10 xl:pt-40rem",
        link: "/steps",
        hasAnimation: false,
    },
    {
        id: "running-in-a-dream",
        isVideo: false,
        images: [
            "/images/Running In a Dream.jpg",
            "/images/Running In a Dream_Detail_01.jpg",
            "/images/Running In a Dream_Detail_02.jpg",
            "/images/Running In a Dream_Detail_03.jpg",
            "/images/Running In a Dream_Detail_04.jpg",
        ],
        caption: [
            "Running In a Dream",
            "Mixed media",
            "Plywood, colored pencils, fabric, nails",
            "2024"
        ],
        thumbnail: "/images/thumbnails/Running In a Dream_thumb.jpg",
        alt: "Running In a Dream, 2024",
        padding: "pb-10 ",
        link: "",
        hasAnimation: true,
    },
    {
        id: "on-the-tracks",
        isVideo: true,
        images: [
            "/images/JooEon_Park_OnTheTracks_main.JPEG",
            "/images/JooEon_Park_OnTheTracks_01.JPEG",
            "/images/JooEon_Park_OnTheTracks_02.JPEG",
            "/images/JooEon_Park_OnTheTracks_03.JPEG",
            "/images/JooEon_Park_OnTheTracks_04.JPEG",
            "/images/JooEon_Park_OnTheTracks_05.JPEG",
            "/images/JooEon_Park_OnTheTracks_06.JPEG",
            "/images/JooEon_Park_OnTheTracks_07.JPEG",
            "/images/JooEon_Park_OnTheTracks_08.JPEG",
            "/images/JooEon_Park_OnTheTracks_09.JPEG",
            "/images/JooEon_Park_OnTheTracks_10.jpg",
            "/images/JooEon_Park_OnTheTracks_16.JPEG",
            "/images/JooEon_Park_OnTheTracks_10.JPEG",
        ],
        caption: [
            "On The Tracks",
            "Street art",
            "Paint, ink, cardboard, tape",
            "2024",
        ],
        thumbnail: "/videos/JooEon_Park_OnTheTracks_Video.MOV",
        alt: "On The Tracks",
        padding: "pb-10 xl:pt-60rem",
        link: "",
        hasAnimation: false,
    },
    {
        id: "recollection",
        isVideo: false,
        images: [
            "/images/Recollection_main.jpg",
            "/images/Recollection_01.jpg",
            "/images/Recollection_02.jpg",
            "/images/Recollection_03.jpg",
        ],
        caption: [
            "Recollection",
            "Drawing",
            "Ink, collage, plastic film",
            "2024"
        ],
        thumbnail: "/images/thumbnails/Recollection_thumb.jpg",
        alt: "Recollection",
        padding: "pb-10 ",
        link: "",
        hasAnimation: true,
    },
    {
        id: "encapsulated",
        isVideo: false,
        images: [
            "/images/JooEon_Park_Encapsulation_03.jpg",
            "/images/JooEon_Park_Encapsulation_05.jpg",
            "/images/JooEon_Park_Encapsulation_06.jpg",
            "/images/JooEon_Park_Encapsulation_11.jpg",
            "/images/JooEon_Park_Encapsulation_13.jpg",
        ],
        caption: [
            "Encapsulated",
            "Artist Book",
            "Folded construction paper and card stock, etching and collagraph",
            "2024"
        ],
        thumbnail: "/images/thumbnails/JooEon_Park_Encapsulation_thumb.jpg",
        alt: "Encapsulated, 2024",
        padding: "",
        link: "",
        hasAnimation: false,
    },
    {
        id: "the-workers",
        isVideo: false,
        images: [
            "/images/The_Workers.jpg",
        ],
        caption: [
            "The Workers",
            "Printmaking",
            "Linocut",
            "2023"
        ],
        thumbnail: "/images/thumbnails/The_Workers_thumb.jpg",
        alt: "The Workers",
        padding: "pb-10 xl:pt-40rem",
        link: "",
        hasAnimation: false,
    },
    {
        id: "trapped",
        isVideo: false,
        images: [
            "/images/Trapped.jpg",
        ],
        caption: [
            "Trapped",
            "Printmaking",
            "Collagraph",
            "2023"
        ],
        thumbnail:  "/images/thumbnails/Trapped_thumb.jpg",
        alt: "Trapped",
        padding: "pb-10 ",
        link: "",
        hasAnimation: false,
    },
    {
        id: "behind-you",
        isVideo: false,
        images: [
            "/images/BehindYou!.jpg",
        ],
        caption: [
            "Behind You!",
            "Printmaking",
            "CMYK Screenprint",
            "2023"
        ],
        thumbnail:  "/images/thumbnails/BehindYou!_thumb.jpg",
        alt: "Behind You!",
        padding: "",
        link: "",
        hasAnimation: false,
    },
    {
        id: "man-child",
        isVideo: false,
        images: [
            "/images/Man-child_main.jpg",
            "/images/Man-child_alt1.jpg",
            "/images/Man-child_alt2.jpg",
            "/images/Man-child_alt3.jpg",
            "/images/Man-child_alt4.jpg",
        ],
        caption: [
            "Man-child",
            "Printmaking",
            "Woodcut",
            "2023"
        ],
        thumbnail: "/images/thumbnails/Man-child_thumb.jpg",
        alt: "Man-child",
        padding: "pb-10 xl:pt-96",
        link: "",
        hasAnimation: false,
    },
    {
        id: "symbiosis",
        isVideo: false,
        images: [
            "/images/Symbiosis.jpg",
        ],
        caption: [
            "Symbiosis",
            "Printmaking",
            "Linocut",
            "2020"
        ],
        thumbnail: "/images/thumbnails/Symbiosis_thumb.jpg",
        alt: "Symbiosis",
        padding: "pb-10 ",
        link: "",
        hasAnimation: false,
    },
];
