export const items = [
    {
        id: "ocular-prosthetic",
        nextItem: "steps",
        isVideo: false,
        images: [
            "/images/Ocular Prosthetic for Reading Another Human_01.jpg",
            "/images/Ocular Prosthetic for Reading Another Human_02.jpg",
        ],
        videos: [],
        caption: [
            "Ocular Prosthetic for Reading Another Human",
            "Sculpture",
            "Plastic tubing over wire attached to a pair of glasses",
            "2024",
            "Inspired by the universal struggle to communicate and understand human thoughts and emotions",
        ],
        thumbnail: "/images/thumbnails/Ocular Prosthetic for Reading Another Human_thumb.jpg",
        alt: "Ocular Prosthetic for Reading Another Human",
        padding: "pb-10 ",
        link: "/project/ocular-prosthetic",
        hasAnimation: true,
    },
    {
        id: "steps",
        nextItem: "running-in-a-dream",
        isVideo: true,
        images: [
            "/images/Steps_Detail_01.jpg",
            "/images/Steps_Detail_02.jpg",
        ],
        videos: [
            "/videos/steps_tv.mp4",
            "/videos/simple.mp4"
        ],
        caption: [
            "11,182,156 Steps",
            "Digital",
            "Display on Toshiba 1979 TV with DVD player and speaker",
            "2024",
            "An audiovisual translation of my daily step counts since January 1st, 2018 to December 2nd, 2024",
        ],
        thumbnail: "/videos/polychrome_dark.mp4",
        alt: "11,182,156 Steps",
        padding: "pb-10 xl:pt-40rem",
        link: "/project/steps",
        hasAnimation: false,
    },
    {
        id: "running-in-a-dream",
        nextItem: "on-the-tracks",
        isVideo: false,
        images: [
            "/images/Running In a Dream.jpg",
            "/images/Running In a Dream_Detail_01.jpg",
            "/images/Running In a Dream_Detail_02.jpg",
            "/images/Running In a Dream_Detail_03.jpg",
            "/images/Running In a Dream_Detail_04.jpg",
        ],
        videos: [],
        caption: [
            "Running In a Dream",
            "Mixed Media",
            "Colored pencil on plywood, attached fabric with nails",
            "2024",
            "Have you ever tried running in a dream?",
        ],
        thumbnail: "/images/Running In a Dream.jpg",
        alt: "Running In a Dream, 2024",
        padding: "pb-10 ",
        link: "/project/running-in-a-dream",
        hasAnimation: true,
    },
    {
        id: "on-the-tracks",
        nextItem: "recollection",
        isVideo: true,
        images: [
            "/images/JooEon_Park_OnTheTracks_main.JPEG",
            "/images/JooEon_Park_OnTheTracks_01.JPEG",
            "/images/JooEon_Park_OnTheTracks_02.JPEG",
            "/images/JooEon_Park_OnTheTracks_03.JPEG",
            "/images/JooEon_Park_OnTheTracks_04.JPEG",
            "/images/JooEon_Park_OnTheTracks_05.JPEG",
            "/images/JooEon_Park_OnTheTracks_06.JPEG",
            "/images/JooEon_Park_OnTheTracks_07.JPEG",
            "/images/JooEon_Park_OnTheTracks_08.JPEG",
            "/images/JooEon_Park_OnTheTracks_09.JPEG",
            "/images/JooEon_Park_OnTheTracks_10.jpg",
            "/images/JooEon_Park_OnTheTracks_16.JPEG",
            "/images/JooEon_Park_OnTheTracks_10.JPEG",
        ],
        videos: [
            "/videos/JooEon_Park_OnTheTracks_Video.MOV",
        ],
        caption: [
            "On The Tracks",
            "Street Art",
            "Paint and sharpie on cardboard attached to public surfaces with tape",
            "2024",
            "Urban intervention in the subway systems of NYC",
        ],
        thumbnail: "/videos/JooEon_Park_OnTheTracks_Video.MOV",
        alt: "On The Tracks",
        padding: "pb-10 xl:pt-60rem",
        link: "/project/on-the-tracks",
        hasAnimation: false,
    },
    {
        id: "recollection",
        nextItem: "encapsulated",
        isVideo: false,
        images: [
            "/images/Recollection_main.jpg",
            "/images/Recollection_01.jpg",
            "/images/Recollection_02.jpg",
            "/images/Recollection_03.jpg",
        ],
        videos: [],
        caption: [
            "Recollection",
            "Drawing & Collage",
            "Ink and collage on illustration board, ink on plastic film",
            "2024",
            "Exhibited at the \"Frame of Mind\" exhibition at Field Projects Gallery, New York, NY",
        ],
        thumbnail: "/images/thumbnails/Recollection_thumb.jpg",
        alt: "Recollection",
        padding: "pb-10 ",
        link: "/project/recollection",
        hasAnimation: true,
    },
    {
        id: "encapsulated",
        nextItem: "the-workers",
        isVideo: false,
        images: [
            "/images/JooEon_Park_Encapsulation_03.jpg",
            "/images/JooEon_Park_Encapsulation_05.jpg",
            "/images/JooEon_Park_Encapsulation_06.jpg",
            "/images/JooEon_Park_Encapsulation_11.jpg",
            "/images/JooEon_Park_Encapsulation_13.jpg",
            "/images/JooEon_Park_Encapsulation_16.jpg"
        ],
        videos: [],
        caption: [
            "Encapsulated",
            "Artist Book",
            "Etching and collagraph prints on card stock encased in folded construction paper",
            "2024",
            "A series of experiences represented through fourteen unique prints, arranged and enclosed in a book",
        ],
        thumbnail: "/images/thumbnails/JooEon_Park_Encapsulation_thumb.jpg",
        alt: "Encapsulated, 2024",
        padding: "",
        link: "/project/encapsulated",
        hasAnimation: false,
    },
    {
        id: "the-workers",
        nextItem: "trapped",
        isVideo: false,
        images: [
            "/images/The_Workers.jpg",
        ],
        videos: [],
        caption: [
            "The Workers",
            "Printmaking",
            "Linocut",
            "2023",
            "N/A",
        ],
        thumbnail: "/images/thumbnails/The_Workers_thumb.jpg",
        alt: "The Workers",
        padding: "pb-10 xl:pt-40rem",
        link: "/project/the-workers",
        hasAnimation: false,
    },
    {
        id: "trapped",
        nextItem: "behind-you",
        isVideo: false,
        images: [
            "/images/Trapped.jpg",
        ],
        videos: [],
        caption: [
            "Trapped",
            "Printmaking",
            "Collagraph with strings, textiles, cardboard, and artist tape",
            "2023",
            "An impression using the collagraph technique folded into an accordion book"
        ],
        thumbnail:  "/images/thumbnails/Trapped_thumb.jpg",
        alt: "Trapped",
        padding: "pb-10 ",
        link: "/project/trapped",
        hasAnimation: false,
    },
    {
        id: "behind-you",
        nextItem: "man-child",
        isVideo: false,
        images: [
            "/images/BehindYou!.jpg",
        ],
        videos: [],
        caption: [
            "Behind You!",
            "Printmaking",
            "CMYK Screenprint",
            "2023",
            "Original paper collage digitally scanned and transferred to a mesh screen for printing",
        ],
        thumbnail:  "/images/thumbnails/BehindYou!_thumb.jpg",
        alt: "Behind You!",
        padding: "",
        link: "/project/behind-you",
        hasAnimation: false,
    },
    {
        id: "man-child",
        nextItem: "symbiosis",
        isVideo: false,
        images: [
            "/images/Man-child_main.jpg",
            "/images/Man-child_alt1.jpg",
            "/images/Man-child_alt2.jpg",
            "/images/Man-child_alt3.jpg",
            "/images/Man-child_alt4.jpg",
            "/images/Man-child_exhibit_01.jpg",
            "/images/Man-child_exhibit_02.jpg",
            "/images/Man-child_exhibit_03.jpg",
        ],
        videos: [],
        caption: [
            "Man-child",
            "Printmaking",
            "Woodcut",
            "2023",
            "Exhibited at the \"One Heart: Korean Art and History Across the Pacific\" exhibition at Wailoa Center, Hilo, HI.",
        ],
        thumbnail: "/images/thumbnails/Man-child_thumb.jpg",
        alt: "Man-child",
        padding: "pb-10 xl:pt-96",
        link: "/project/man-child",
        hasAnimation: false,
    },
    {
        id: "symbiosis",
        nextItem: "ocular-prosthetic",
        isVideo: false,
        images: [
            "/images/Symbiosis.jpg",
            "/images/Symbiosis_closeup.jpg",
        ],
        videos: [],
        caption: [
            "Symbiosis",
            "Printmaking",
            "Linocut",
            "2020",
            "Tessellation depicting the symbiotic relationship of two contrasting entities",
        ],
        thumbnail: "/images/thumbnails/Symbiosis_thumb.jpg",
        alt: "Symbiosis",
        padding: "pb-10 ",
        link: "/project/symbiosis",
        hasAnimation: false,
    },
];
